"""add translate model

Revision ID: 0da8223327d1
Revises: 942c4b2327c4
Create Date: 2024-11-17 10:57:41.970076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da8223327d1'
down_revision = '942c4b2327c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('targetID', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget_transaction', schema=None) as batch_op:
        batch_op.drop_column('targetID')

    # ### end Alembic commands ###
