"""Update Questions model

Revision ID: 1586cf727942
Revises: 4209c68583b1
Create Date: 2023-12-04 20:18:24.874076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1586cf727942'
down_revision = '4209c68583b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###
