"""donation track columns

Revision ID: 168b1c524df9
Revises: 779fc7cdb469
Create Date: 2024-08-18 14:50:19.841120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168b1c524df9'
down_revision = '779fc7cdb469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('closed')

    # ### end Alembic commands ###
