"""added donor fields

Revision ID: 1b4657d490d6
Revises: 45e17c4e25c5
Create Date: 2024-02-21 21:04:41.507416

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b4657d490d6"
down_revision = "45e17c4e25c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("donationType", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("caseID", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("projectID", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "projects_data", ["projectID"], ["projectID"])
        batch_op.create_foreign_key(None, "cases_data", ["caseID"], ["caseID"])

    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("phoneNumber", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.drop_column("phoneNumber")
        batch_op.drop_column("email")

    with op.batch_alter_table("donations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("projectID")
        batch_op.drop_column("caseID")
        batch_op.drop_column("donationType")

    # ### end Alembic commands ###
