"""unique email in user model

Revision ID: 212016d5f57a
Revises: 3289b145e0ad
Create Date: 2024-11-09 10:51:35.913833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212016d5f57a'
down_revision = '3289b145e0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
