"""added active

Revision ID: 273fc35b80b9
Revises: 35151b1a60a9
Create Date: 2024-03-28 08:13:46.656837

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "273fc35b80b9"
down_revision = "35151b1a60a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects_data", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
