"""init migration2

Revision ID: 4209c68583b1
Revises: 
Create Date: 2023-12-02 22:38:38.616148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4209c68583b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projectID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'projects', ['projectID'], ['projectID'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('questions_projectID_fkey', type_='foreignkey')
        batch_op.drop_column('projectID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projectID', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('questions_projectID_fkey', 'projects', ['projectID'], ['projectID'])

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('projectID')

    # ### end Alembic commands ###
