"""addedImageLink

Revision ID: 427efb9d1422
Revises: 4e5060d602a9
Create Date: 2024-07-07 14:20:58.385732

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "427efb9d1422"
down_revision = "4e5060d602a9"
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("imageLink", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("imageLink")

    # ### end Alembic commands ###
