"""more finance models

Revision ID: 45e17c4e25c5
Revises: 27171826ac9d
Create Date: 2024-02-18 18:08:04.476271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e17c4e25c5'
down_revision = '27171826ac9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('donorID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('donorType', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('donorID')
    )
    op.create_table('financial_fund',
    sa.Column('fundID', sa.Integer(), nullable=False),
    sa.Column('fundName', sa.String(), nullable=False),
    sa.Column('totalFund', sa.Float(), nullable=False),
    sa.Column('usedFund', sa.Float(), nullable=True),
    sa.Column('accountType', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('fundID')
    )
    op.create_table('payments',
    sa.Column('paymentID', sa.Integer(), nullable=False),
    sa.Column('from_fund', sa.Integer(), nullable=True),
    sa.Column('paymentFor', sa.Enum('CASE', 'OTHER', name='paymentfor'), nullable=False),
    sa.Column('paymentName', sa.String(), nullable=True),
    sa.Column('paymentMethod', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_fund'], ['financial_fund.fundID'], ),
    sa.PrimaryKeyConstraint('paymentID')
    )
    op.create_table('region_account',
    sa.Column('accountID', sa.Integer(), nullable=False),
    sa.Column('accountName', sa.String(), nullable=False),
    sa.Column('totalFund', sa.Float(), nullable=False),
    sa.Column('usedFund', sa.Float(), nullable=False),
    sa.Column('accountType', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lastTransation', sa.Date(), nullable=True),
    sa.Column('health_funds', sa.Float(), nullable=True),
    sa.Column('education_funds', sa.Float(), nullable=True),
    sa.Column('general_funds', sa.Float(), nullable=True),
    sa.Column('shelter_funds', sa.Float(), nullable=True),
    sa.Column('sponsorship_funds', sa.Float(), nullable=True),
    sa.Column('regionID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regionID'], ['regions.regionID'], ),
    sa.PrimaryKeyConstraint('accountID')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donorID', sa.Integer(), nullable=False),
    sa.Column('accountID', sa.Integer(), nullable=False),
    sa.Column('fundID', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accountID'], ['region_account.accountID'], ),
    sa.ForeignKeyConstraint(['donorID'], ['donors.donorID'], ),
    sa.ForeignKeyConstraint(['fundID'], ['financial_fund.fundID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_transfer_requests',
    sa.Column('requestID', sa.Integer(), nullable=False),
    sa.Column('from_fund', sa.Integer(), nullable=True),
    sa.Column('to_fund', sa.Integer(), nullable=True),
    sa.Column('transferAmount', sa.Float(), nullable=False),
    sa.Column('requestedBy', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.Enum('ASSESSMENT', 'ONGOING', 'APPROVED', name='transferstage'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachedFiles', sa.String(), nullable=True),
    sa.Column('approvedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_fund'], ['financial_fund.fundID'], ),
    sa.ForeignKeyConstraint(['requestedBy'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['to_fund'], ['financial_fund.fundID'], ),
    sa.PrimaryKeyConstraint('requestID')
    )
    op.create_table('case_fund_release_requests',
    sa.Column('requestID', sa.Integer(), nullable=False),
    sa.Column('caseID', sa.Integer(), nullable=False),
    sa.Column('fundsRequested', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('requestedBy', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approvedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caseID'], ['cases_data.caseID'], ),
    sa.ForeignKeyConstraint(['requestedBy'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('requestID')
    )
    op.create_table('case_funds',
    sa.Column('fundID', sa.Integer(), nullable=False),
    sa.Column('caseID', sa.Integer(), nullable=False),
    sa.Column('fundsAllocated', sa.Float(), nullable=True),
    sa.Column('accountID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountID'], ['region_account.accountID'], ),
    sa.ForeignKeyConstraint(['caseID'], ['cases_data.caseID'], ),
    sa.PrimaryKeyConstraint('fundID')
    )
    op.create_table('project_fund_release_requests',
    sa.Column('requestID', sa.Integer(), nullable=False),
    sa.Column('projectID', sa.Integer(), nullable=False),
    sa.Column('fundsRequested', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('requestedBy', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approvedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projectID'], ['projects_data.projectID'], ),
    sa.ForeignKeyConstraint(['requestedBy'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('requestID')
    )
    op.create_table('project_funds',
    sa.Column('fundID', sa.Integer(), nullable=False),
    sa.Column('projectID', sa.Integer(), nullable=False),
    sa.Column('fundsAllocated', sa.Float(), nullable=True),
    sa.Column('accountID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountID'], ['region_account.accountID'], ),
    sa.ForeignKeyConstraint(['projectID'], ['projects_data.projectID'], ),
    sa.PrimaryKeyConstraint('fundID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_funds')
    op.drop_table('project_fund_release_requests')
    op.drop_table('case_funds')
    op.drop_table('case_fund_release_requests')
    op.drop_table('fund_transfer_requests')
    op.drop_table('donations')
    op.drop_table('region_account')
    op.drop_table('payments')
    op.drop_table('financial_fund')
    op.drop_table('donors')
    # ### end Alembic commands ###
