"""added budget approved to case

Revision ID: 4a085feaa902
Revises: b7de54626fd8
Create Date: 2024-01-31 07:52:15.100254

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a085feaa902"
down_revision = "b7de54626fd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("budgetApproved", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases_data", schema=None) as batch_op:
        batch_op.drop_column("budgetApproved")

    # ### end Alembic commands ###
