"""updateCaseStatusData

Revision ID: 51c96b7e68e7
Revises: c2765ba07063
Create Date: 2024-07-15 14:47:15.301633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51c96b7e68e7'
down_revision = 'c2765ba07063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_status_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))


    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('pdfBytes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdfBytes', postgresql.BYTEA(), autoincrement=False, nullable=False))

   

    with op.batch_alter_table('case_status_data', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
