"""new case task to user models

Revision ID: 5d5e9f9ee3c7
Revises: 243cc1689c33
Create Date: 2024-02-03 09:46:45.420391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5e9f9ee3c7'
down_revision = '243cc1689c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_task_assigned_to',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['case_task.taskID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_task_cc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['case_task.taskID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('c_task_cc')
    op.drop_table('c_task_assigned_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_task_assigned_to',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['case_task.taskID'], name='c_task_assigned_to_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.userID'], name='c_task_assigned_to_user_id_fkey'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name='c_task_assigned_to_pkey')
    )
    op.create_table('c_task_cc',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['case_task.taskID'], name='c_task_cc_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.userID'], name='c_task_cc_user_id_fkey'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name='c_task_cc_pkey')
    )
    op.drop_table('case_task_cc')
    op.drop_table('case_task_assigned_to')
    # ### end Alembic commands ###
