"""20june

Revision ID: 63ada844dc93
Revises: 715cc51d378f
Create Date: 2024-06-20 18:51:26.270961

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "63ada844dc93"
down_revision = "715cc51d378f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_funds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("accountID", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["accountID"],
            ["region_account.accountID"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fund_transfer_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "transferType",
            existing_type=postgresql.ENUM("EFT", "CASH", "CHECK", name="paymentmethod"),
            type_=sa.Enum("EFT", "CASH", "CHECK", name="paymentmethod"),
            existing_nullable=True,
        )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subFundID", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "paymentMethod",
            existing_type=postgresql.ENUM("EFT", "CASH", "CHECK", name="paymentmethod"),
            type_=sa.Enum("EFT", "CASH", "CHECK", name="paymentmethod"),
            existing_nullable=True,
        )
        batch_op.create_foreign_key(None, "sub_funds", ["subFundID"], ["subFundID"])

    with op.batch_alter_table("region_account_transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("region_account_transactions", schema=None) as batch_op:
        batch_op.drop_column("category")

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "paymentMethod",
            existing_type=sa.Enum("EFT", "CASH", "CHECK", name="transfertype"),
            type_=postgresql.ENUM("EFT", "CASH", "CHECK", name="paymentmethod"),
            existing_nullable=True,
        )
        batch_op.drop_column("subFundID")

    with op.batch_alter_table("fund_transfer_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "transferType",
            existing_type=sa.Enum("EFT", "CASH", "CHECK", name="transfertype"),
            type_=postgresql.ENUM("EFT", "CASH", "CHECK", name="paymentmethod"),
            existing_nullable=True,
        )

    op.drop_table("category_funds")
    # ### end Alembic commands ###
