"""modified beneficiary

Revision ID: 645ecaec106d
Revises: 38ac3dab1bcf
Create Date: 2024-08-09 14:43:24.359017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '645ecaec106d'
down_revision = '38ac3dab1bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numberOfPayments', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.drop_column('numberOfPayments')

    op.create_table('payments',
    sa.Column('paymentID', sa.INTEGER(), server_default=sa.text('nextval(\'"payments_paymentID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('from_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paymentFor', postgresql.ENUM('CASE', 'OTHER', name='paymentfor'), autoincrement=False, nullable=False),
    sa.Column('paymentName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paymentMethod', postgresql.ENUM('EFT', 'CASH', 'CHECK', name='paymentmethod'), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('transferExpenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currencyID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectScope', postgresql.ENUM('HEALTH', 'SHELTER', 'EDUCATION', 'GENERAL', 'SPONSORSHIP', 'RELIEF', name='projectscopes'), autoincrement=False, nullable=True),
    sa.Column('subFundID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['currencyID'], ['currencies.currencyID'], name='payments_currencyID_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_fund'], ['financial_fund.fundID'], name='payments_from_fund_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subFundID'], ['sub_funds.subFundID'], name='payments_subFundID_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paymentID', name='payments_pkey')
    )
    # ### end Alembic commands ###
