"""Added UserTask model and related changes

Revision ID: 70d74a4d29c2
Revises: 0e907379a526
Create Date: 2024-11-03 01:35:36.669510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70d74a4d29c2'
down_revision = '0e907379a526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_task',
    sa.Column('taskID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'INPROGRESS', 'DONE', 'OVERDUE', name='usertaskstatus'), nullable=False),
    sa.Column('completionDate', sa.Date(), nullable=True),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('taskID')
    )
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.alter_column('stageID',
               existing_type=sa.INTEGER())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.alter_column('stageID',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('user_task')
    # ### end Alembic commands ###
