"""august beneficiary update

Revision ID: 779fc7cdb469
Revises: f876cdeea236
Create Date: 2024-08-14 20:45:01.472690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779fc7cdb469'
down_revision = 'f876cdeea236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regionId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('otherRegion', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'regions', ['regionId'], ['regionID'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('otherRegion')
        batch_op.drop_column('regionId')

    # ### end Alembic commands ###
