"""added unique constraint

Revision ID: 7f80676c1feb
Revises: 168b1c524df9
Create Date: 2024-08-21 20:55:22.172971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f80676c1feb'
down_revision = '168b1c524df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary_form', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['caseID'])

    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['caseID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('beneficiary_form', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
