"""added cascade

Revision ID: 825da7dfe951
Revises: 427efb9d1422
Create Date: 2024-07-10 18:28:07.235611

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "825da7dfe951"
down_revision = "427efb9d1422"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_constraint("activities_programID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "projects_data", ["programID"], ["projectID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("activity_users", schema=None) as batch_op:
        batch_op.drop_constraint("activity_users_activityID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "activities", ["activityID"], ["activityID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("assessment_answers", schema=None) as batch_op:
        batch_op.drop_constraint(
            "assessment_answers_projectID_fkey", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "assessment_answers_questionID_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "projects_data", ["projectID"], ["projectID"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None,
            "assessment_questions",
            ["questionID"],
            ["questionID"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("case_assessment_answers", schema=None) as batch_op:
        batch_op.drop_constraint(
            "case_assessment_answers_caseID_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "cases_data", ["caseID"], ["caseID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("case_status_data", schema=None) as batch_op:
        batch_op.drop_constraint("case_status_data_caseID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "cases_data", ["caseID"], ["caseID"], ondelete="CASCADE"
        )
        batch_op.drop_column("status")

    with op.batch_alter_table("case_task", schema=None) as batch_op:
        batch_op.drop_constraint("case_task_caseID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "cases_data", ["caseID"], ["caseID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("case_task_assigned_to", schema=None) as batch_op:
        batch_op.drop_constraint(
            "case_task_assigned_to_task_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "case_task", ["task_id"], ["taskID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("case_task_cc", schema=None) as batch_op:
        batch_op.drop_constraint("case_task_cc_task_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "case_task", ["task_id"], ["taskID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("case_task_comments", schema=None) as batch_op:
        batch_op.drop_constraint("case_task_comments_taskID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "case_task", ["taskID"], ["taskID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("case_to_stage", schema=None) as batch_op:
        batch_op.drop_constraint("case_to_stage_caseID_fkey", type_="foreignkey")
        batch_op.drop_constraint("case_to_stage_stageID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "cases_data", ["caseID"], ["caseID"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "case_stage", ["stageID"], ["stageID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("case_users", schema=None) as batch_op:
        batch_op.drop_constraint("case_users_caseID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "cases_data", ["caseID"], ["caseID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_stage", schema=None) as batch_op:
        batch_op.drop_constraint("project_stage_projectID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "projects_data", ["projectID"], ["projectID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_status_data", schema=None) as batch_op:
        batch_op.drop_constraint(
            "project_status_data_projectID_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "projects_data", ["projectID"], ["projectID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_task", schema=None) as batch_op:
        batch_op.drop_constraint("project_task_projectID_fkey", type_="foreignkey")
        batch_op.drop_constraint("project_task_stageID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "projects_data", ["projectID"], ["projectID"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "stage", ["stageID"], ["stageID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_task_assigned_to", schema=None) as batch_op:
        batch_op.drop_constraint(
            "project_task_assigned_to_task_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "project_task", ["task_id"], ["taskID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_task_cc", schema=None) as batch_op:
        batch_op.drop_constraint("project_task_cc_task_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "project_task", ["task_id"], ["taskID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_user", schema=None) as batch_op:
        batch_op.drop_constraint("project_user_projectID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "projects_data", ["projectID"], ["projectID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("question_choices", schema=None) as batch_op:
        batch_op.drop_constraint("question_choices_questionID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "questions", ["questionID"], ["questionID"], ondelete="CASCADE"
        )

    with op.batch_alter_table("task_comments", schema=None) as batch_op:
        batch_op.drop_constraint("task_comments_taskID_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "project_task", ["taskID"], ["taskID"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_comments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "task_comments_taskID_fkey", "project_task", ["taskID"], ["taskID"]
        )

    with op.batch_alter_table("question_choices", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "question_choices_questionID_fkey",
            "questions",
            ["questionID"],
            ["questionID"],
        )

    with op.batch_alter_table("project_user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_user_projectID_fkey", "projects_data", ["projectID"], ["projectID"]
        )

    with op.batch_alter_table("project_task_cc", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_task_cc_task_id_fkey", "project_task", ["task_id"], ["taskID"]
        )

    with op.batch_alter_table("project_task_assigned_to", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_task_assigned_to_task_id_fkey",
            "project_task",
            ["task_id"],
            ["taskID"],
        )

    with op.batch_alter_table("project_task", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_task_stageID_fkey", "stage", ["stageID"], ["stageID"]
        )
        batch_op.create_foreign_key(
            "project_task_projectID_fkey", "projects_data", ["projectID"], ["projectID"]
        )

    with op.batch_alter_table("project_status_data", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_status_data_projectID_fkey",
            "projects_data",
            ["projectID"],
            ["projectID"],
        )

    with op.batch_alter_table("project_stage", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_stage_projectID_fkey",
            "projects_data",
            ["projectID"],
            ["projectID"],
        )

    with op.batch_alter_table("case_users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_users_caseID_fkey", "cases_data", ["caseID"], ["caseID"]
        )

    with op.batch_alter_table("case_to_stage", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_to_stage_stageID_fkey", "case_stage", ["stageID"], ["stageID"]
        )
        batch_op.create_foreign_key(
            "case_to_stage_caseID_fkey", "cases_data", ["caseID"], ["caseID"]
        )

    with op.batch_alter_table("case_task_comments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_task_comments_taskID_fkey", "case_task", ["taskID"], ["taskID"]
        )

    with op.batch_alter_table("case_task_cc", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_task_cc_task_id_fkey", "case_task", ["task_id"], ["taskID"]
        )

    with op.batch_alter_table("case_task_assigned_to", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_task_assigned_to_task_id_fkey", "case_task", ["task_id"], ["taskID"]
        )

    with op.batch_alter_table("case_task", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_task_caseID_fkey", "cases_data", ["caseID"], ["caseID"]
        )

    with op.batch_alter_table("case_status_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_status_data_caseID_fkey", "cases_data", ["caseID"], ["caseID"]
        )

    with op.batch_alter_table("case_assessment_answers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "case_assessment_answers_caseID_fkey", "cases_data", ["caseID"], ["caseID"]
        )

    with op.batch_alter_table("assessment_answers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "assessment_answers_questionID_fkey",
            "assessment_questions",
            ["questionID"],
            ["questionID"],
        )
        batch_op.create_foreign_key(
            "assessment_answers_projectID_fkey",
            "projects_data",
            ["projectID"],
            ["projectID"],
        )

    with op.batch_alter_table("activity_users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "activity_users_activityID_fkey",
            "activities",
            ["activityID"],
            ["activityID"],
        )

    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "activities_programID_fkey", "projects_data", ["programID"], ["projectID"]
        )

    # ### end Alembic commands ###
