"""imageLinksToDonor

Revision ID: 8285f6f440af
Revises: 51c96b7e68e7
Create Date: 2024-07-21 13:05:09.128469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8285f6f440af'
down_revision = '51c96b7e68e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageLink', sa.String(), nullable=True))

    

    with op.batch_alter_table('representatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageLink', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('representatives', schema=None) as batch_op:
        batch_op.drop_column('imageLink')

    

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('imageLink')

    # ### end Alembic commands ###
