"""mod reports

Revision ID: 866e1764e4f5
Revises: dd033a47100e
Create Date: 2024-07-26 18:35:02.759065

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "866e1764e4f5"
down_revision = "dd033a47100e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("reportId", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pdfUrl", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_column("pdfUrl")
        batch_op.drop_column("reportId")
        batch_op.drop_column("type")

    # ### end Alembic commands ###
