"""update translate model

Revision ID: 8fa2691fb248
Revises: 171464f8fc69
Create Date: 2024-11-11 08:10:37.070051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa2691fb248'
down_revision = '171464f8fc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('translations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_column('service_description')
        batch_op.drop_column('recommendations')
        batch_op.drop_column('credit_info')
        batch_op.drop_column('media_note')
        batch_op.drop_column('documents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('media_note', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('credit_info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('translations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###
