"""casebeneficiary modified

Revision ID: 92d2fbaecc2c
Revises: 5d5e9f9ee3c7
Create Date: 2024-02-09 14:06:21.083662

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92d2fbaecc2c"
down_revision = "5d5e9f9ee3c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case_beneficiary", schema=None) as batch_op:
        batch_op.add_column(sa.Column("surname", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("gender", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("birthDate", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("birthPlace", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("nationality", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("idType", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("idNumber", sa.String(), nullable=False))

    with op.batch_alter_table("cases_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_points", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases_data", schema=None) as batch_op:
        batch_op.drop_column("total_points")

    with op.batch_alter_table("case_beneficiary", schema=None) as batch_op:
        batch_op.drop_column("idNumber")
        batch_op.drop_column("idType")
        batch_op.drop_column("nationality")
        batch_op.drop_column("birthPlace")
        batch_op.drop_column("birthDate")
        batch_op.drop_column("gender")
        batch_op.drop_column("surname")

    # ### end Alembic commands ###
