"""user budget

Revision ID: a8e6c3a2110d
Revises: ff0c63893ec8
Create Date: 2024-09-04 19:39:34.118158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e6c3a2110d'
down_revision = 'ff0c63893ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_budget',
    sa.Column('budgetId', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('currencyID', sa.Integer(), nullable=False),
    sa.Column('totalFund', sa.Float(), nullable=False),
    sa.Column('usedFund', sa.Float(), nullable=False),
    sa.Column('availableFund', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['currencyID'], ['currencies.currencyID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budgetId')
    )
    with op.batch_alter_table('user_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_budget_currencyID'), ['currencyID'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_budget_userID'), ['userID'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_budget_userID'))
        batch_op.drop_index(batch_op.f('ix_user_budget_currencyID'))

    op.drop_table('user_budget')
    # ### end Alembic commands ###
