"""Add the stage table

Revision ID: a9697b412ba6
Revises: aef7aed93f88
Create Date: 2023-12-24 12:02:33.204179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9697b412ba6'
down_revision = 'aef7aed93f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('stageID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('stageID')
    )
    op.create_table('project_stages',
    sa.Column('projectID', sa.Integer(), nullable=False),
    sa.Column('stageID', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completionDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['projectID'], ['projects.projectID'], ),
    sa.ForeignKeyConstraint(['stageID'], ['stages.stageID'], ),
    sa.PrimaryKeyConstraint('projectID', 'stageID')
    )
    op.create_table('project_tasks',
    sa.Column('taskID', sa.Integer(), nullable=False),
    sa.Column('projectID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=False),
    sa.Column('attachedFiles', sa.String(), nullable=True),
    sa.Column('stageID', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completionDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['projectID'], ['projects.projectID'], ),
    sa.ForeignKeyConstraint(['stageID'], ['stages.stageID'], ),
    sa.PrimaryKeyConstraint('taskID')
    )
    op.create_table('task_assigned_to',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.taskID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.userID'], )
    )
    op.create_table('task_cc',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.taskID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.userID'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_cc')
    op.drop_table('task_assigned_to')
    op.drop_table('project_tasks')
    op.drop_table('project_stages')
    op.drop_table('stages')
    # ### end Alembic commands ###
