"""Update Answer model

Revision ID: aef7aed93f88
Revises: 1586cf727942
Create Date: 2023-12-04 22:37:16.487243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef7aed93f88'
down_revision = '1586cf727942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choiceID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'question_choices', ['choiceID'], ['choiceID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('choiceID')

    # ### end Alembic commands ###
