"""user budget on hold

Revision ID: b5cb621f8468
Revises: e8d6124eeed3
Create Date: 2024-11-16 11:46:24.368275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cb621f8468'
down_revision = 'e8d6124eeed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onHoldFund', sa.Float(), nullable=False, server_default="0.0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget', schema=None) as batch_op:
        batch_op.drop_column('onHoldFund')

    # ### end Alembic commands ###
