"""changed question10

Revision ID: b7de54626fd8
Revises: af9541d41f58
Create Date: 2024-01-30 21:53:28.216315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7de54626fd8'
down_revision = 'af9541d41f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases_data', schema=None) as batch_op:
        # Drop the existing column
        batch_op.drop_column('question10')

    # Add the new column with the desired type
    op.add_column('cases_data', sa.Column('question10', postgresql.JSONB(astext_type=sa.Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases_data', schema=None) as batch_op:
        # Drop the new column
        batch_op.drop_column('question10')

    # Add the old column with the previous type
    op.add_column('cases_data', sa.Column('question10', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
