"""more cascade

Revision ID: c2765ba07063
Revises: 825da7dfe951
Create Date: 2024-07-11 15:56:59.013281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2765ba07063'
down_revision = '825da7dfe951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary_form', schema=None) as batch_op:
        batch_op.drop_constraint('beneficiary_form_caseID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cases_data', ['caseID'], ['caseID'], ondelete='CASCADE')

    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.drop_constraint('case_beneficiary_caseID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cases_data', ['caseID'], ['caseID'], ondelete='CASCADE')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('case_beneficiary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_beneficiary_caseID_fkey', 'cases_data', ['caseID'], ['caseID'])

    with op.batch_alter_table('beneficiary_form', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('beneficiary_form_caseID_fkey', 'cases_data', ['caseID'], ['caseID'])

    # ### end Alembic commands ###
