"""added order column to case questions

Revision ID: c9ef3732d9f7
Revises: 1eb3cdc32aeb
Create Date: 2024-01-12 22:32:23.415940

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9ef3732d9f7"
down_revision = "1eb3cdc32aeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cquestions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cquestions", schema=None) as batch_op:
        batch_op.drop_column("order")

    # ### end Alembic commands ###
