"""update translate model

Revision ID: e8d6124eeed3
Revises: 8fa2691fb248
Create Date: 2024-11-11 08:22:27.823977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8d6124eeed3'
down_revision = '8fa2691fb248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('translated', sa.Text(), nullable=True),
    sa.Column('translate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('translations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))

    op.drop_table('translation_contents')
    # ### end Alembic commands ###
