"""add status to transcations

Revision ID: ed2dfa3f1e30
Revises: 0da8223327d1
Create Date: 2024-11-17 11:58:30.040222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2dfa3f1e30'
down_revision = '0da8223327d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget_transaction', schema=None) as batch_op:
        # Add the column with nullable=True initially
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE user_budget_transaction SET status = 'PENDING'")

    # Alter the column to be NOT NULL
    with op.batch_alter_table('user_budget_transaction', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget_transaction', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
