"""activity added

Revision ID: f23654ad92ce
Revises: 0a22594ad801
Create Date: 2024-03-26 17:18:24.150093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23654ad92ce'
down_revision = '0a22594ad801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_data', schema=None) as batch_op:
        batch_op.execute("""
            CREATE TYPE protype AS ENUM ('PROJECT', 'PROGRAM');
        """)
    op.create_table('activities',
    sa.Column('activityID', sa.Integer(), nullable=False),
    sa.Column('activityName', sa.String(), nullable=False),
    sa.Column('regionID', sa.Integer(), nullable=False),
    sa.Column('programID', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('costRequired', sa.Float(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('activityStatus', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='actstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['programID'], ['projects_data.projectID'], ),
    sa.ForeignKeyConstraint(['regionID'], ['regions.regionID'], ),
    sa.PrimaryKeyConstraint('activityID')
    )
    op.create_table('activity_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activityID'], ['activities.activityID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.Enum('PROJECT', 'PROGRAM', name='protype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_data', schema=None) as batch_op:
        batch_op.drop_column('project_type')

    op.drop_table('activity_users')
    op.drop_table('activities')
    # ### end Alembic commands ###
