"""added requirements table

Revision ID: f3f037771a16
Revises: 5c9c8510c71d
Create Date: 2024-01-15 18:51:12.610253

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3f037771a16"
down_revision = "5c9c8510c71d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirements",
        sa.Column("requirementID", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "section",
            sa.Enum("FINANCIAL", "IMPLEMENTATION", "MEDIA", name="requirementsection"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("requirementID"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requirements")
    # ### end Alembic commands ###
