"""beneficiary address

Revision ID: f876cdeea236
Revises: 645ecaec106d
Create Date: 2024-08-11 09:16:15.874083

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f876cdeea236"
down_revision = "645ecaec106d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case_beneficiary", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case_beneficiary", schema=None) as batch_op:
        batch_op.drop_column("address")

    # ### end Alembic commands ###
