"""task comments added

Revision ID: f9c18d8f53f2
Revises: eff733b324aa
Create Date: 2024-01-06 19:56:47.136604

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9c18d8f53f2"
down_revision = "eff733b324aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userID", sa.Integer(), nullable=False),
        sa.Column("taskID", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["taskID"],
            ["project_task.taskID"],
        ),
        sa.ForeignKeyConstraint(
            ["userID"],
            ["users.userID"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # with op.batch_alter_table('project_task', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('status', sa.Enum('TODO', 'INPROGRESS', 'DONE', 'OVERDUE', name='taskstatus'), nullable=False))
    #     batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("status")

    op.drop_table("task_comments")
    # ### end Alembic commands ###
