"""payment totals

Revision ID: ff0c63893ec8
Revises: 7f80676c1feb
Create Date: 2024-08-23 23:25:23.153197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0c63893ec8'
down_revision = '7f80676c1feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approvedPayments', sa.Float(), nullable=True))

    with op.batch_alter_table('projects_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approvedPayments', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_data', schema=None) as batch_op:
        batch_op.drop_column('approvedPayments')

    with op.batch_alter_table('cases_data', schema=None) as batch_op:
        batch_op.drop_column('approvedPayments')

    # ### end Alembic commands ###
